# Generated by Django 5.0.1 on 2024-01-04 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barcode',
            name='code',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
